# Generated by Django 4.1.4 on 2023-02-14 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("Cname", models.CharField(max_length=100)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Student_details",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("f_name", models.CharField(max_length=50)),
                ("l_name", models.CharField(max_length=60)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                (
                    "class_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.class"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subname", models.CharField(max_length=100)),
                ("id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="Student_subjects",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.student_details",
                    ),
                ),
                (
                    "subject_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="app.subject"
                    ),
                ),
            ],
        ),
    ]
